packages:
  - 'app/*'
allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': false
  '@scarf/scarf': false
  '@sentry/cli': false
  '@swc/core': false
  msgpackr-extract: false
  prisma: false
  sharp: false
  unrs-resolver: false
